//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace RSSFeedService
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(FEED))]
    public partial class CATEGORY: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public long category_id
        {
            get { return _category_id; }
            set
            {
                if (_category_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'category_id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _category_id = value;
                    OnPropertyChanged("category_id");
                }
            }
        }
        private long _category_id;
    
        [DataMember]
        public string category_name
        {
            get { return _category_name; }
            set
            {
                if (_category_name != value)
                {
                    _category_name = value;
                    OnPropertyChanged("category_name");
                }
            }
        }
        private string _category_name;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<FEED> FEED
        {
            get
            {
                if (_fEED == null)
                {
                    _fEED = new TrackableCollection<FEED>();
                    _fEED.CollectionChanged += FixupFEED;
                }
                return _fEED;
            }
            set
            {
                if (!ReferenceEquals(_fEED, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_fEED != null)
                    {
                        _fEED.CollectionChanged -= FixupFEED;
                    }
                    _fEED = value;
                    if (_fEED != null)
                    {
                        _fEED.CollectionChanged += FixupFEED;
                    }
                    OnNavigationPropertyChanged("FEED");
                }
            }
        }
        private TrackableCollection<FEED> _fEED;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            FEED.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupFEED(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (FEED item in e.NewItems)
                {
                    item.CATEGORY = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("FEED", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (FEED item in e.OldItems)
                {
                    if (ReferenceEquals(item.CATEGORY, this))
                    {
                        item.CATEGORY = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("FEED", item);
                    }
                }
            }
        }

        #endregion
    }
}
