//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSFeedModel.RSSAccountManagerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USER", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class USER : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.ObjectChangeTracker ChangeTrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfFEEDAjaB2cDg FEEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfITEMAjaB2cDg ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.ROLE ROLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.STATUS STATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long role_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long status_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short user_connectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfFEEDAjaB2cDg FEED {
            get {
                return this.FEEDField;
            }
            set {
                if ((object.ReferenceEquals(this.FEEDField, value) != true)) {
                    this.FEEDField = value;
                    this.RaisePropertyChanged("FEED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfITEMAjaB2cDg ITEM {
            get {
                return this.ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEMField, value) != true)) {
                    this.ITEMField = value;
                    this.RaisePropertyChanged("ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.ROLE ROLE {
            get {
                return this.ROLEField;
            }
            set {
                if ((object.ReferenceEquals(this.ROLEField, value) != true)) {
                    this.ROLEField = value;
                    this.RaisePropertyChanged("ROLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.STATUS STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSField, value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long role_id {
            get {
                return this.role_idField;
            }
            set {
                if ((this.role_idField.Equals(value) != true)) {
                    this.role_idField = value;
                    this.RaisePropertyChanged("role_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long status_id {
            get {
                return this.status_idField;
            }
            set {
                if ((this.status_idField.Equals(value) != true)) {
                    this.status_idField = value;
                    this.RaisePropertyChanged("status_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short user_connected {
            get {
                return this.user_connectedField;
            }
            set {
                if ((this.user_connectedField.Equals(value) != true)) {
                    this.user_connectedField = value;
                    this.RaisePropertyChanged("user_connected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_email {
            get {
                return this.user_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.user_emailField, value) != true)) {
                    this.user_emailField = value;
                    this.RaisePropertyChanged("user_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_key {
            get {
                return this.user_keyField;
            }
            set {
                if ((object.ReferenceEquals(this.user_keyField, value) != true)) {
                    this.user_keyField = value;
                    this.RaisePropertyChanged("user_key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_password {
            get {
                return this.user_passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.user_passwordField, value) != true)) {
                    this.user_passwordField = value;
                    this.RaisePropertyChanged("user_password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectChangeTracker", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ObjectChangeTracker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.ExtendedPropertiesDictionary ExtendedPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.ObjectsAddedToCollectionProperties ObjectsAddedToCollectionPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.ObjectsRemovedFromCollectionProperties ObjectsRemovedFromCollectionPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.OriginalValuesDictionary OriginalValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.ObjectState StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.ExtendedPropertiesDictionary ExtendedProperties {
            get {
                return this.ExtendedPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedPropertiesField, value) != true)) {
                    this.ExtendedPropertiesField = value;
                    this.RaisePropertyChanged("ExtendedProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.ObjectsAddedToCollectionProperties ObjectsAddedToCollectionProperties {
            get {
                return this.ObjectsAddedToCollectionPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsAddedToCollectionPropertiesField, value) != true)) {
                    this.ObjectsAddedToCollectionPropertiesField = value;
                    this.RaisePropertyChanged("ObjectsAddedToCollectionProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.ObjectsRemovedFromCollectionProperties ObjectsRemovedFromCollectionProperties {
            get {
                return this.ObjectsRemovedFromCollectionPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsRemovedFromCollectionPropertiesField, value) != true)) {
                    this.ObjectsRemovedFromCollectionPropertiesField = value;
                    this.RaisePropertyChanged("ObjectsRemovedFromCollectionProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.OriginalValuesDictionary OriginalValues {
            get {
                return this.OriginalValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalValuesField, value) != true)) {
                    this.OriginalValuesField = value;
                    this.RaisePropertyChanged("OriginalValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.ObjectState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ROLE", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ROLE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.ObjectChangeTracker ChangeTrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfUSERAjaB2cDg USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long role_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string role_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfUSERAjaB2cDg USER {
            get {
                return this.USERField;
            }
            set {
                if ((object.ReferenceEquals(this.USERField, value) != true)) {
                    this.USERField = value;
                    this.RaisePropertyChanged("USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long role_id {
            get {
                return this.role_idField;
            }
            set {
                if ((this.role_idField.Equals(value) != true)) {
                    this.role_idField = value;
                    this.RaisePropertyChanged("role_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string role_name {
            get {
                return this.role_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.role_nameField, value) != true)) {
                    this.role_nameField = value;
                    this.RaisePropertyChanged("role_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STATUS", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class STATUS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.ObjectChangeTracker ChangeTrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfUSERAjaB2cDg USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long status_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string status_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfUSERAjaB2cDg USER {
            get {
                return this.USERField;
            }
            set {
                if ((object.ReferenceEquals(this.USERField, value) != true)) {
                    this.USERField = value;
                    this.RaisePropertyChanged("USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long status_id {
            get {
                return this.status_idField;
            }
            set {
                if ((this.status_idField.Equals(value) != true)) {
                    this.status_idField = value;
                    this.RaisePropertyChanged("status_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status_name {
            get {
                return this.status_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.status_nameField, value) != true)) {
                    this.status_nameField = value;
                    this.RaisePropertyChanged("status_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfFEEDAjaB2cDg", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="FEED")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfFEEDAjaB2cDg : System.Collections.Generic.List<RSSFeedModel.RSSAccountManagerService.FEED> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfITEMAjaB2cDg", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="ITEM")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfITEMAjaB2cDg : System.Collections.Generic.List<RSSFeedModel.RSSAccountManagerService.ITEM> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExtendedPropertiesDictionary", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="ExtendedProperties", KeyName="Name", ValueName="ExtendedProperty")]
    [System.SerializableAttribute()]
    public class ExtendedPropertiesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsAddedToCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="AddedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="AddedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsAddedToCollectionProperties : System.Collections.Generic.Dictionary<string, RSSFeedModel.RSSAccountManagerService.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsRemovedFromCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="DeletedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="DeletedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsRemovedFromCollectionProperties : System.Collections.Generic.Dictionary<string, RSSFeedModel.RSSAccountManagerService.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OriginalValuesDictionary", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="OriginalValues", KeyName="Name", ValueName="OriginalValue")]
    [System.SerializableAttribute()]
    public class OriginalValuesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectState", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService")]
    public enum ObjectState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectList", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="ObjectValue")]
    [System.SerializableAttribute()]
    public class ObjectList : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FEED", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class FEED : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.CATEGORY CATEGORYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.ObjectChangeTracker ChangeTrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfITEMAjaB2cDg ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfUSERAjaB2cDg USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> category_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string feed_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string feed_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long feed_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string feed_linkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string feed_titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.CATEGORY CATEGORY {
            get {
                return this.CATEGORYField;
            }
            set {
                if ((object.ReferenceEquals(this.CATEGORYField, value) != true)) {
                    this.CATEGORYField = value;
                    this.RaisePropertyChanged("CATEGORY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfITEMAjaB2cDg ITEM {
            get {
                return this.ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEMField, value) != true)) {
                    this.ITEMField = value;
                    this.RaisePropertyChanged("ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfUSERAjaB2cDg USER {
            get {
                return this.USERField;
            }
            set {
                if ((object.ReferenceEquals(this.USERField, value) != true)) {
                    this.USERField = value;
                    this.RaisePropertyChanged("USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> category_id {
            get {
                return this.category_idField;
            }
            set {
                if ((this.category_idField.Equals(value) != true)) {
                    this.category_idField = value;
                    this.RaisePropertyChanged("category_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string feed_address {
            get {
                return this.feed_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.feed_addressField, value) != true)) {
                    this.feed_addressField = value;
                    this.RaisePropertyChanged("feed_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string feed_description {
            get {
                return this.feed_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.feed_descriptionField, value) != true)) {
                    this.feed_descriptionField = value;
                    this.RaisePropertyChanged("feed_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long feed_id {
            get {
                return this.feed_idField;
            }
            set {
                if ((this.feed_idField.Equals(value) != true)) {
                    this.feed_idField = value;
                    this.RaisePropertyChanged("feed_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string feed_link {
            get {
                return this.feed_linkField;
            }
            set {
                if ((object.ReferenceEquals(this.feed_linkField, value) != true)) {
                    this.feed_linkField = value;
                    this.RaisePropertyChanged("feed_link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string feed_title {
            get {
                return this.feed_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.feed_titleField, value) != true)) {
                    this.feed_titleField = value;
                    this.RaisePropertyChanged("feed_title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CATEGORY", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CATEGORY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.ObjectChangeTracker ChangeTrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfFEEDAjaB2cDg FEEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long category_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfFEEDAjaB2cDg FEED {
            get {
                return this.FEEDField;
            }
            set {
                if ((object.ReferenceEquals(this.FEEDField, value) != true)) {
                    this.FEEDField = value;
                    this.RaisePropertyChanged("FEED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long category_id {
            get {
                return this.category_idField;
            }
            set {
                if ((this.category_idField.Equals(value) != true)) {
                    this.category_idField = value;
                    this.RaisePropertyChanged("category_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category_name {
            get {
                return this.category_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.category_nameField, value) != true)) {
                    this.category_nameField = value;
                    this.RaisePropertyChanged("category_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfUSERAjaB2cDg", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="USER")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfUSERAjaB2cDg : System.Collections.Generic.List<RSSFeedModel.RSSAccountManagerService.USER> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ITEM", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ITEM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.ObjectChangeTracker ChangeTrackerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.FEED FEEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfUSERAjaB2cDg USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long feed_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long item_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_linkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.ObjectChangeTracker ChangeTracker {
            get {
                return this.ChangeTrackerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeTrackerField, value) != true)) {
                    this.ChangeTrackerField = value;
                    this.RaisePropertyChanged("ChangeTracker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.FEED FEED {
            get {
                return this.FEEDField;
            }
            set {
                if ((object.ReferenceEquals(this.FEEDField, value) != true)) {
                    this.FEEDField = value;
                    this.RaisePropertyChanged("FEED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.RSSAccountManagerService.TrackableCollectionOfUSERAjaB2cDg USER {
            get {
                return this.USERField;
            }
            set {
                if ((object.ReferenceEquals(this.USERField, value) != true)) {
                    this.USERField = value;
                    this.RaisePropertyChanged("USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long feed_id {
            get {
                return this.feed_idField;
            }
            set {
                if ((this.feed_idField.Equals(value) != true)) {
                    this.feed_idField = value;
                    this.RaisePropertyChanged("feed_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_description {
            get {
                return this.item_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.item_descriptionField, value) != true)) {
                    this.item_descriptionField = value;
                    this.RaisePropertyChanged("item_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long item_id {
            get {
                return this.item_idField;
            }
            set {
                if ((this.item_idField.Equals(value) != true)) {
                    this.item_idField = value;
                    this.RaisePropertyChanged("item_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_link {
            get {
                return this.item_linkField;
            }
            set {
                if ((object.ReferenceEquals(this.item_linkField, value) != true)) {
                    this.item_linkField = value;
                    this.RaisePropertyChanged("item_link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_title {
            get {
                return this.item_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.item_titleField, value) != true)) {
                    this.item_titleField = value;
                    this.RaisePropertyChanged("item_title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RSSAccountManagerService.IRssFeedAccountManager")]
    public interface IRssFeedAccountManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFeedAccountManager/logOn", ReplyAction="http://tempuri.org/IRssFeedAccountManager/logOnResponse")]
        RSSFeedModel.RSSAccountManagerService.USER logOn(string email, string password, short idclient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFeedAccountManager/logOff", ReplyAction="http://tempuri.org/IRssFeedAccountManager/logOffResponse")]
        bool logOff(string email, short idclient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFeedAccountManager/Register", ReplyAction="http://tempuri.org/IRssFeedAccountManager/RegisterResponse")]
        bool Register(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFeedAccountManager/ChangePassword", ReplyAction="http://tempuri.org/IRssFeedAccountManager/ChangePasswordResponse")]
        bool ChangePassword(string email, string password, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFeedAccountManager/ResetPassword", ReplyAction="http://tempuri.org/IRssFeedAccountManager/ResetPasswordResponse")]
        void ResetPassword();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFeedAccountManager/RegisterConfirmation", ReplyAction="http://tempuri.org/IRssFeedAccountManager/RegisterConfirmationResponse")]
        bool RegisterConfirmation(string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRssFeedAccountManagerChannel : RSSFeedModel.RSSAccountManagerService.IRssFeedAccountManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RssFeedAccountManagerClient : System.ServiceModel.ClientBase<RSSFeedModel.RSSAccountManagerService.IRssFeedAccountManager>, RSSFeedModel.RSSAccountManagerService.IRssFeedAccountManager {
        
        public RssFeedAccountManagerClient() {
        }
        
        public RssFeedAccountManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RssFeedAccountManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssFeedAccountManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssFeedAccountManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RSSFeedModel.RSSAccountManagerService.USER logOn(string email, string password, short idclient) {
            return base.Channel.logOn(email, password, idclient);
        }
        
        public bool logOff(string email, short idclient) {
            return base.Channel.logOff(email, idclient);
        }
        
        public bool Register(string email, string password) {
            return base.Channel.Register(email, password);
        }
        
        public bool ChangePassword(string email, string password, string newPassword) {
            return base.Channel.ChangePassword(email, password, newPassword);
        }
        
        public void ResetPassword() {
            base.Channel.ResetPassword();
        }
        
        public bool RegisterConfirmation(string key) {
            return base.Channel.RegisterConfirmation(key);
        }
    }
}
