//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSFeedDesktop.ParserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ParserService.IFeedParser")]
    public interface IFeedParser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedParser/parseFeed", ReplyAction="http://tempuri.org/IFeedParser/parseFeedResponse")]
        bool parseFeed(string myUrl, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedParser/deleteFeed", ReplyAction="http://tempuri.org/IFeedParser/deleteFeedResponse")]
        void deleteFeed(int id, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedParser/readFeed", ReplyAction="http://tempuri.org/IFeedParser/readFeedResponse")]
        void readFeed(int id, string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeedParserChannel : RSSFeedDesktop.ParserService.IFeedParser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeedParserClient : System.ServiceModel.ClientBase<RSSFeedDesktop.ParserService.IFeedParser>, RSSFeedDesktop.ParserService.IFeedParser {
        
        public FeedParserClient() {
        }
        
        public FeedParserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeedParserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedParserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedParserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool parseFeed(string myUrl, string email) {
            return base.Channel.parseFeed(myUrl, email);
        }
        
        public void deleteFeed(int id, string email) {
            base.Channel.deleteFeed(id, email);
        }
        
        public void readFeed(int id, string email) {
            base.Channel.readFeed(id, email);
        }
    }
}
