//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSFeedOutlook.AccountService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientType", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedAccountManager")]
    public enum ClientType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoClient = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebClient = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DesktopClient = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MobileClient = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.IAccountManager")]
    public interface IAccountManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/logOn", ReplyAction="http://tempuri.org/IAccountManager/logOnResponse")]
        bool logOn(string email, string password, RSSFeedOutlook.AccountService.ClientType clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/logOff", ReplyAction="http://tempuri.org/IAccountManager/logOffResponse")]
        bool logOff(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/Register", ReplyAction="http://tempuri.org/IAccountManager/RegisterResponse")]
        bool Register(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/ChangePassword", ReplyAction="http://tempuri.org/IAccountManager/ChangePasswordResponse")]
        bool ChangePassword(string email, string password, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/ResetPassword", ReplyAction="http://tempuri.org/IAccountManager/ResetPasswordResponse")]
        void ResetPassword();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/RegisterConfirmation", ReplyAction="http://tempuri.org/IAccountManager/RegisterConfirmationResponse")]
        bool RegisterConfirmation(string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountManagerChannel : RSSFeedOutlook.AccountService.IAccountManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountManagerClient : System.ServiceModel.ClientBase<RSSFeedOutlook.AccountService.IAccountManager>, RSSFeedOutlook.AccountService.IAccountManager {
        
        public AccountManagerClient() {
        }
        
        public AccountManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool logOn(string email, string password, RSSFeedOutlook.AccountService.ClientType clientId) {
            return base.Channel.logOn(email, password, clientId);
        }
        
        public bool logOff(string email) {
            return base.Channel.logOff(email);
        }
        
        public bool Register(string email, string password) {
            return base.Channel.Register(email, password);
        }
        
        public bool ChangePassword(string email, string password, string newPassword) {
            return base.Channel.ChangePassword(email, password, newPassword);
        }
        
        public void ResetPassword() {
            base.Channel.ResetPassword();
        }
        
        public bool RegisterConfirmation(string key) {
            return base.Channel.RegisterConfirmation(key);
        }
    }
}
