//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSFeedWeb.RSSAccountManagerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExtendedPropertiesDictionary", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="ExtendedProperties", KeyName="Name", ValueName="ExtendedProperty")]
    [System.SerializableAttribute()]
    public class ExtendedPropertiesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsAddedToCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="AddedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="AddedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsAddedToCollectionProperties : System.Collections.Generic.Dictionary<string, RSSFeedWeb.RSSAccountManagerService.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectList", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="ObjectValue")]
    [System.SerializableAttribute()]
    public class ObjectList : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsRemovedFromCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="DeletedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="DeletedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsRemovedFromCollectionProperties : System.Collections.Generic.Dictionary<string, RSSFeedWeb.RSSAccountManagerService.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OriginalValuesDictionary", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="OriginalValues", KeyName="Name", ValueName="OriginalValue")]
    [System.SerializableAttribute()]
    public class OriginalValuesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfFEEDAjaB2cDg", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="FEED")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfFEEDAjaB2cDg : System.Collections.Generic.List<RSSFeedModel.RSSAccountManagerService.FEED> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfITEMAjaB2cDg", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="ITEM")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfITEMAjaB2cDg : System.Collections.Generic.List<RSSFeedModel.RSSAccountManagerService.ITEM> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfUSERAjaB2cDg", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedService", ItemName="USER")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfUSERAjaB2cDg : System.Collections.Generic.List<RSSFeedModel.RSSAccountManagerService.USER> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RSSAccountManagerService.IRssFeedAccountManager")]
    public interface IRssFeedAccountManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFeedAccountManager/logOn", ReplyAction="http://tempuri.org/IRssFeedAccountManager/logOnResponse")]
        RSSFeedModel.RSSAccountManagerService.USER logOn(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFeedAccountManager/logOff", ReplyAction="http://tempuri.org/IRssFeedAccountManager/logOffResponse")]
        bool logOff(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFeedAccountManager/Register", ReplyAction="http://tempuri.org/IRssFeedAccountManager/RegisterResponse")]
        bool Register(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFeedAccountManager/ChangePassword", ReplyAction="http://tempuri.org/IRssFeedAccountManager/ChangePasswordResponse")]
        bool ChangePassword(string email, string password, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssFeedAccountManager/ResetPassword", ReplyAction="http://tempuri.org/IRssFeedAccountManager/ResetPasswordResponse")]
        void ResetPassword();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRssFeedAccountManagerChannel : RSSFeedWeb.RSSAccountManagerService.IRssFeedAccountManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RssFeedAccountManagerClient : System.ServiceModel.ClientBase<RSSFeedWeb.RSSAccountManagerService.IRssFeedAccountManager>, RSSFeedWeb.RSSAccountManagerService.IRssFeedAccountManager {
        
        public RssFeedAccountManagerClient() {
        }
        
        public RssFeedAccountManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RssFeedAccountManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssFeedAccountManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssFeedAccountManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RSSFeedModel.RSSAccountManagerService.USER logOn(string email, string password) {
            return base.Channel.logOn(email, password);
        }
        
        public bool logOff(string email) {
            return base.Channel.logOff(email);
        }
        
        public bool Register(string email, string password) {
            return base.Channel.Register(email, password);
        }
        
        public bool ChangePassword(string email, string password, string newPassword) {
            return base.Channel.ChangePassword(email, password, newPassword);
        }
        
        public void ResetPassword() {
            base.Channel.ResetPassword();
        }
    }
}
