//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace RSSFeedData
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(FEED))]
    [KnownType(typeof(USER))]
    public partial class ITEM: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public long item_id
        {
            get { return _item_id; }
            set
            {
                if (_item_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'item_id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _item_id = value;
                    OnPropertyChanged("item_id");
                }
            }
        }
        private long _item_id;
    
        [DataMember]
        public string item_title
        {
            get { return _item_title; }
            set
            {
                if (_item_title != value)
                {
                    _item_title = value;
                    OnPropertyChanged("item_title");
                }
            }
        }
        private string _item_title;
    
        [DataMember]
        public string item_link
        {
            get { return _item_link; }
            set
            {
                if (_item_link != value)
                {
                    _item_link = value;
                    OnPropertyChanged("item_link");
                }
            }
        }
        private string _item_link;
    
        [DataMember]
        public string item_description
        {
            get { return _item_description; }
            set
            {
                if (_item_description != value)
                {
                    _item_description = value;
                    OnPropertyChanged("item_description");
                }
            }
        }
        private string _item_description;
    
        [DataMember]
        public long feed_id
        {
            get { return _feed_id; }
            set
            {
                if (_feed_id != value)
                {
                    ChangeTracker.RecordOriginalValue("feed_id", _feed_id);
                    if (!IsDeserializing)
                    {
                        if (FEED != null && FEED.feed_id != value)
                        {
                            FEED = null;
                        }
                    }
                    _feed_id = value;
                    OnPropertyChanged("feed_id");
                }
            }
        }
        private long _feed_id;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public FEED FEED
        {
            get { return _fEED; }
            set
            {
                if (!ReferenceEquals(_fEED, value))
                {
                    var previousValue = _fEED;
                    _fEED = value;
                    FixupFEED(previousValue);
                    OnNavigationPropertyChanged("FEED");
                }
            }
        }
        private FEED _fEED;
    
        [DataMember]
        public TrackableCollection<USER> USER
        {
            get
            {
                if (_uSER == null)
                {
                    _uSER = new TrackableCollection<USER>();
                    _uSER.CollectionChanged += FixupUSER;
                }
                return _uSER;
            }
            set
            {
                if (!ReferenceEquals(_uSER, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_uSER != null)
                    {
                        _uSER.CollectionChanged -= FixupUSER;
                    }
                    _uSER = value;
                    if (_uSER != null)
                    {
                        _uSER.CollectionChanged += FixupUSER;
                    }
                    OnNavigationPropertyChanged("USER");
                }
            }
        }
        private TrackableCollection<USER> _uSER;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            FEED = null;
            USER.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupFEED(FEED previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.ITEM.Contains(this))
            {
                previousValue.ITEM.Remove(this);
            }
    
            if (FEED != null)
            {
                if (!FEED.ITEM.Contains(this))
                {
                    FEED.ITEM.Add(this);
                }
    
                feed_id = FEED.feed_id;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("FEED")
                    && (ChangeTracker.OriginalValues["FEED"] == FEED))
                {
                    ChangeTracker.OriginalValues.Remove("FEED");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("FEED", previousValue);
                }
                if (FEED != null && !FEED.ChangeTracker.ChangeTrackingEnabled)
                {
                    FEED.StartTracking();
                }
            }
        }
    
        private void FixupUSER(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (USER item in e.NewItems)
                {
                    if (!item.ITEM.Contains(this))
                    {
                        item.ITEM.Add(this);
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("USER", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (USER item in e.OldItems)
                {
                    if (item.ITEM.Contains(this))
                    {
                        item.ITEM.Remove(this);
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("USER", item);
                    }
                }
            }
        }

        #endregion
    }
}
