//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSFeedModel.AccountService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientType", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedAccountManager")]
    public enum ClientType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoClient = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebClient = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DesktopClient = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MobileClient = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USER", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedAccountManager.DataService")]
    [System.SerializableAttribute()]
    public partial class USER : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.AccountService.FEED[] FEEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.AccountService.ITEM[] ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.AccountService.ROLE ROLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.AccountService.STATUS STATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long role_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long status_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short user_connectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.AccountService.FEED[] FEED {
            get {
                return this.FEEDField;
            }
            set {
                if ((object.ReferenceEquals(this.FEEDField, value) != true)) {
                    this.FEEDField = value;
                    this.RaisePropertyChanged("FEED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.AccountService.ITEM[] ITEM {
            get {
                return this.ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEMField, value) != true)) {
                    this.ITEMField = value;
                    this.RaisePropertyChanged("ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.AccountService.ROLE ROLE {
            get {
                return this.ROLEField;
            }
            set {
                if ((object.ReferenceEquals(this.ROLEField, value) != true)) {
                    this.ROLEField = value;
                    this.RaisePropertyChanged("ROLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.AccountService.STATUS STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSField, value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long role_id {
            get {
                return this.role_idField;
            }
            set {
                if ((this.role_idField.Equals(value) != true)) {
                    this.role_idField = value;
                    this.RaisePropertyChanged("role_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long status_id {
            get {
                return this.status_idField;
            }
            set {
                if ((this.status_idField.Equals(value) != true)) {
                    this.status_idField = value;
                    this.RaisePropertyChanged("status_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short user_connected {
            get {
                return this.user_connectedField;
            }
            set {
                if ((this.user_connectedField.Equals(value) != true)) {
                    this.user_connectedField = value;
                    this.RaisePropertyChanged("user_connected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_email {
            get {
                return this.user_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.user_emailField, value) != true)) {
                    this.user_emailField = value;
                    this.RaisePropertyChanged("user_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_key {
            get {
                return this.user_keyField;
            }
            set {
                if ((object.ReferenceEquals(this.user_keyField, value) != true)) {
                    this.user_keyField = value;
                    this.RaisePropertyChanged("user_key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_password {
            get {
                return this.user_passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.user_passwordField, value) != true)) {
                    this.user_passwordField = value;
                    this.RaisePropertyChanged("user_password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ROLE", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedAccountManager.DataService")]
    [System.SerializableAttribute()]
    public partial class ROLE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.AccountService.USER[] USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long role_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string role_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.AccountService.USER[] USER {
            get {
                return this.USERField;
            }
            set {
                if ((object.ReferenceEquals(this.USERField, value) != true)) {
                    this.USERField = value;
                    this.RaisePropertyChanged("USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long role_id {
            get {
                return this.role_idField;
            }
            set {
                if ((this.role_idField.Equals(value) != true)) {
                    this.role_idField = value;
                    this.RaisePropertyChanged("role_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string role_name {
            get {
                return this.role_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.role_nameField, value) != true)) {
                    this.role_nameField = value;
                    this.RaisePropertyChanged("role_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STATUS", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedAccountManager.DataService")]
    [System.SerializableAttribute()]
    public partial class STATUS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.AccountService.USER[] USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long status_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string status_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.AccountService.USER[] USER {
            get {
                return this.USERField;
            }
            set {
                if ((object.ReferenceEquals(this.USERField, value) != true)) {
                    this.USERField = value;
                    this.RaisePropertyChanged("USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long status_id {
            get {
                return this.status_idField;
            }
            set {
                if ((this.status_idField.Equals(value) != true)) {
                    this.status_idField = value;
                    this.RaisePropertyChanged("status_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status_name {
            get {
                return this.status_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.status_nameField, value) != true)) {
                    this.status_nameField = value;
                    this.RaisePropertyChanged("status_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FEED", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedAccountManager.DataService")]
    [System.SerializableAttribute()]
    public partial class FEED : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.AccountService.CATEGORY CATEGORYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.AccountService.ITEM[] ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.AccountService.USER[] USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> category_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string feed_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string feed_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long feed_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string feed_linkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string feed_titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.AccountService.CATEGORY CATEGORY {
            get {
                return this.CATEGORYField;
            }
            set {
                if ((object.ReferenceEquals(this.CATEGORYField, value) != true)) {
                    this.CATEGORYField = value;
                    this.RaisePropertyChanged("CATEGORY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.AccountService.ITEM[] ITEM {
            get {
                return this.ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEMField, value) != true)) {
                    this.ITEMField = value;
                    this.RaisePropertyChanged("ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.AccountService.USER[] USER {
            get {
                return this.USERField;
            }
            set {
                if ((object.ReferenceEquals(this.USERField, value) != true)) {
                    this.USERField = value;
                    this.RaisePropertyChanged("USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> category_id {
            get {
                return this.category_idField;
            }
            set {
                if ((this.category_idField.Equals(value) != true)) {
                    this.category_idField = value;
                    this.RaisePropertyChanged("category_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string feed_address {
            get {
                return this.feed_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.feed_addressField, value) != true)) {
                    this.feed_addressField = value;
                    this.RaisePropertyChanged("feed_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string feed_description {
            get {
                return this.feed_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.feed_descriptionField, value) != true)) {
                    this.feed_descriptionField = value;
                    this.RaisePropertyChanged("feed_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long feed_id {
            get {
                return this.feed_idField;
            }
            set {
                if ((this.feed_idField.Equals(value) != true)) {
                    this.feed_idField = value;
                    this.RaisePropertyChanged("feed_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string feed_link {
            get {
                return this.feed_linkField;
            }
            set {
                if ((object.ReferenceEquals(this.feed_linkField, value) != true)) {
                    this.feed_linkField = value;
                    this.RaisePropertyChanged("feed_link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string feed_title {
            get {
                return this.feed_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.feed_titleField, value) != true)) {
                    this.feed_titleField = value;
                    this.RaisePropertyChanged("feed_title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ITEM", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedAccountManager.DataService")]
    [System.SerializableAttribute()]
    public partial class ITEM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.AccountService.FEED FEEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.AccountService.USER[] USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long feed_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long item_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_linkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.AccountService.FEED FEED {
            get {
                return this.FEEDField;
            }
            set {
                if ((object.ReferenceEquals(this.FEEDField, value) != true)) {
                    this.FEEDField = value;
                    this.RaisePropertyChanged("FEED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.AccountService.USER[] USER {
            get {
                return this.USERField;
            }
            set {
                if ((object.ReferenceEquals(this.USERField, value) != true)) {
                    this.USERField = value;
                    this.RaisePropertyChanged("USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long feed_id {
            get {
                return this.feed_idField;
            }
            set {
                if ((this.feed_idField.Equals(value) != true)) {
                    this.feed_idField = value;
                    this.RaisePropertyChanged("feed_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_description {
            get {
                return this.item_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.item_descriptionField, value) != true)) {
                    this.item_descriptionField = value;
                    this.RaisePropertyChanged("item_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long item_id {
            get {
                return this.item_idField;
            }
            set {
                if ((this.item_idField.Equals(value) != true)) {
                    this.item_idField = value;
                    this.RaisePropertyChanged("item_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_link {
            get {
                return this.item_linkField;
            }
            set {
                if ((object.ReferenceEquals(this.item_linkField, value) != true)) {
                    this.item_linkField = value;
                    this.RaisePropertyChanged("item_link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_title {
            get {
                return this.item_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.item_titleField, value) != true)) {
                    this.item_titleField = value;
                    this.RaisePropertyChanged("item_title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CATEGORY", Namespace="http://schemas.datacontract.org/2004/07/RSSFeedAccountManager.DataService")]
    [System.SerializableAttribute()]
    public partial class CATEGORY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RSSFeedModel.AccountService.FEED[] FEEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long category_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RSSFeedModel.AccountService.FEED[] FEED {
            get {
                return this.FEEDField;
            }
            set {
                if ((object.ReferenceEquals(this.FEEDField, value) != true)) {
                    this.FEEDField = value;
                    this.RaisePropertyChanged("FEED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long category_id {
            get {
                return this.category_idField;
            }
            set {
                if ((this.category_idField.Equals(value) != true)) {
                    this.category_idField = value;
                    this.RaisePropertyChanged("category_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category_name {
            get {
                return this.category_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.category_nameField, value) != true)) {
                    this.category_nameField = value;
                    this.RaisePropertyChanged("category_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.IAccountManager")]
    public interface IAccountManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/logOn", ReplyAction="http://tempuri.org/IAccountManager/logOnResponse")]
        RSSFeedModel.AccountService.USER logOn(string email, string password, RSSFeedModel.AccountService.ClientType clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/logOff", ReplyAction="http://tempuri.org/IAccountManager/logOffResponse")]
        bool logOff(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/Register", ReplyAction="http://tempuri.org/IAccountManager/RegisterResponse")]
        bool Register(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/ChangePassword", ReplyAction="http://tempuri.org/IAccountManager/ChangePasswordResponse")]
        bool ChangePassword(string email, string password, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/ResetPassword", ReplyAction="http://tempuri.org/IAccountManager/ResetPasswordResponse")]
        void ResetPassword();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/RegisterConfirmation", ReplyAction="http://tempuri.org/IAccountManager/RegisterConfirmationResponse")]
        bool RegisterConfirmation(string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountManagerChannel : RSSFeedModel.AccountService.IAccountManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountManagerClient : System.ServiceModel.ClientBase<RSSFeedModel.AccountService.IAccountManager>, RSSFeedModel.AccountService.IAccountManager {
        
        public AccountManagerClient() {
        }
        
        public AccountManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RSSFeedModel.AccountService.USER logOn(string email, string password, RSSFeedModel.AccountService.ClientType clientId) {
            return base.Channel.logOn(email, password, clientId);
        }
        
        public bool logOff(string email) {
            return base.Channel.logOff(email);
        }
        
        public bool Register(string email, string password) {
            return base.Channel.Register(email, password);
        }
        
        public bool ChangePassword(string email, string password, string newPassword) {
            return base.Channel.ChangePassword(email, password, newPassword);
        }
        
        public void ResetPassword() {
            base.Channel.ResetPassword();
        }
        
        public bool RegisterConfirmation(string key) {
            return base.Channel.RegisterConfirmation(key);
        }
    }
}
