//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 03/11/2011 14:48:35
namespace RSSFeedModel.RSSFeedService
{
    
    /// <summary>
    /// There are no comments for RSSFeedDatabaseEntities in the schema.
    /// </summary>
    public partial class RSSFeedDatabaseEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new RSSFeedDatabaseEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSSFeedDatabaseEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("RSSFeedDatabaseModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("RSSFeedModel.RSSFeedService", typeName.Substring(20)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("RSSFeedModel.RSSFeedService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("RSSFeedDatabaseModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for CATEGORY in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CATEGORY> CATEGORY
        {
            get
            {
                if ((this._CATEGORY == null))
                {
                    this._CATEGORY = base.CreateQuery<CATEGORY>("CATEGORY");
                }
                return this._CATEGORY;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CATEGORY> _CATEGORY;
        /// <summary>
        /// There are no comments for FEED in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<FEED> FEED
        {
            get
            {
                if ((this._FEED == null))
                {
                    this._FEED = base.CreateQuery<FEED>("FEED");
                }
                return this._FEED;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<FEED> _FEED;
        /// <summary>
        /// There are no comments for ITEM in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ITEM> ITEM
        {
            get
            {
                if ((this._ITEM == null))
                {
                    this._ITEM = base.CreateQuery<ITEM>("ITEM");
                }
                return this._ITEM;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ITEM> _ITEM;
        /// <summary>
        /// There are no comments for ROLE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ROLE> ROLE
        {
            get
            {
                if ((this._ROLE == null))
                {
                    this._ROLE = base.CreateQuery<ROLE>("ROLE");
                }
                return this._ROLE;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ROLE> _ROLE;
        /// <summary>
        /// There are no comments for STATUS in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<STATUS> STATUS
        {
            get
            {
                if ((this._STATUS == null))
                {
                    this._STATUS = base.CreateQuery<STATUS>("STATUS");
                }
                return this._STATUS;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<STATUS> _STATUS;
        /// <summary>
        /// There are no comments for USER in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<USER> USER
        {
            get
            {
                if ((this._USER == null))
                {
                    this._USER = base.CreateQuery<USER>("USER");
                }
                return this._USER;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<USER> _USER;
        /// <summary>
        /// There are no comments for CATEGORY in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCATEGORY(CATEGORY cATEGORY)
        {
            base.AddObject("CATEGORY", cATEGORY);
        }
        /// <summary>
        /// There are no comments for FEED in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFEED(FEED fEED)
        {
            base.AddObject("FEED", fEED);
        }
        /// <summary>
        /// There are no comments for ITEM in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToITEM(ITEM iTEM)
        {
            base.AddObject("ITEM", iTEM);
        }
        /// <summary>
        /// There are no comments for ROLE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToROLE(ROLE rOLE)
        {
            base.AddObject("ROLE", rOLE);
        }
        /// <summary>
        /// There are no comments for STATUS in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSTATUS(STATUS sTATUS)
        {
            base.AddObject("STATUS", sTATUS);
        }
        /// <summary>
        /// There are no comments for USER in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUSER(USER uSER)
        {
            base.AddObject("USER", uSER);
        }
    }
    /// <summary>
    /// There are no comments for RSSFeedDatabaseModel.CATEGORY in the schema.
    /// </summary>
    /// <KeyProperties>
    /// category_id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CATEGORY")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("category_id")]
    public partial class CATEGORY : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CATEGORY object.
        /// </summary>
        /// <param name="category_id">Initial value of category_id.</param>
        /// <param name="category_name">Initial value of category_name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CATEGORY CreateCATEGORY(long category_id, string category_name)
        {
            CATEGORY cATEGORY = new CATEGORY();
            cATEGORY.category_id = category_id;
            cATEGORY.category_name = category_name;
            return cATEGORY;
        }
        /// <summary>
        /// There are no comments for Property category_id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long category_id
        {
            get
            {
                return this._category_id;
            }
            set
            {
                this.Oncategory_idChanging(value);
                this._category_id = value;
                this.Oncategory_idChanged();
                this.OnPropertyChanged("category_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _category_id;
        partial void Oncategory_idChanging(long value);
        partial void Oncategory_idChanged();
        /// <summary>
        /// There are no comments for Property category_name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string category_name
        {
            get
            {
                return this._category_name;
            }
            set
            {
                this.Oncategory_nameChanging(value);
                this._category_name = value;
                this.Oncategory_nameChanged();
                this.OnPropertyChanged("category_name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _category_name;
        partial void Oncategory_nameChanging(string value);
        partial void Oncategory_nameChanged();
        /// <summary>
        /// There are no comments for FEED in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<FEED> FEED
        {
            get
            {
                return this._FEED;
            }
            set
            {
                this._FEED = value;
                this.OnPropertyChanged("FEED");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<FEED> _FEED = new global::System.Data.Services.Client.DataServiceCollection<FEED>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RSSFeedDatabaseModel.FEED in the schema.
    /// </summary>
    /// <KeyProperties>
    /// feed_id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("FEED")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("feed_id")]
    public partial class FEED : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new FEED object.
        /// </summary>
        /// <param name="feed_id">Initial value of feed_id.</param>
        /// <param name="feed_title">Initial value of feed_title.</param>
        /// <param name="feed_address">Initial value of feed_address.</param>
        /// <param name="feed_link">Initial value of feed_link.</param>
        /// <param name="feed_description">Initial value of feed_description.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static FEED CreateFEED(long feed_id, string feed_title, string feed_address, string feed_link, string feed_description)
        {
            FEED fEED = new FEED();
            fEED.feed_id = feed_id;
            fEED.feed_title = feed_title;
            fEED.feed_address = feed_address;
            fEED.feed_link = feed_link;
            fEED.feed_description = feed_description;
            return fEED;
        }
        /// <summary>
        /// There are no comments for Property feed_id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long feed_id
        {
            get
            {
                return this._feed_id;
            }
            set
            {
                this.Onfeed_idChanging(value);
                this._feed_id = value;
                this.Onfeed_idChanged();
                this.OnPropertyChanged("feed_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _feed_id;
        partial void Onfeed_idChanging(long value);
        partial void Onfeed_idChanged();
        /// <summary>
        /// There are no comments for Property feed_title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string feed_title
        {
            get
            {
                return this._feed_title;
            }
            set
            {
                this.Onfeed_titleChanging(value);
                this._feed_title = value;
                this.Onfeed_titleChanged();
                this.OnPropertyChanged("feed_title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _feed_title;
        partial void Onfeed_titleChanging(string value);
        partial void Onfeed_titleChanged();
        /// <summary>
        /// There are no comments for Property feed_address in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string feed_address
        {
            get
            {
                return this._feed_address;
            }
            set
            {
                this.Onfeed_addressChanging(value);
                this._feed_address = value;
                this.Onfeed_addressChanged();
                this.OnPropertyChanged("feed_address");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _feed_address;
        partial void Onfeed_addressChanging(string value);
        partial void Onfeed_addressChanged();
        /// <summary>
        /// There are no comments for Property feed_link in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string feed_link
        {
            get
            {
                return this._feed_link;
            }
            set
            {
                this.Onfeed_linkChanging(value);
                this._feed_link = value;
                this.Onfeed_linkChanged();
                this.OnPropertyChanged("feed_link");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _feed_link;
        partial void Onfeed_linkChanging(string value);
        partial void Onfeed_linkChanged();
        /// <summary>
        /// There are no comments for Property feed_description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string feed_description
        {
            get
            {
                return this._feed_description;
            }
            set
            {
                this.Onfeed_descriptionChanging(value);
                this._feed_description = value;
                this.Onfeed_descriptionChanged();
                this.OnPropertyChanged("feed_description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _feed_description;
        partial void Onfeed_descriptionChanging(string value);
        partial void Onfeed_descriptionChanged();
        /// <summary>
        /// There are no comments for Property category_id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> category_id
        {
            get
            {
                return this._category_id;
            }
            set
            {
                this.Oncategory_idChanging(value);
                this._category_id = value;
                this.Oncategory_idChanged();
                this.OnPropertyChanged("category_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _category_id;
        partial void Oncategory_idChanging(global::System.Nullable<long> value);
        partial void Oncategory_idChanged();
        /// <summary>
        /// There are no comments for CATEGORY in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CATEGORY CATEGORY
        {
            get
            {
                return this._CATEGORY;
            }
            set
            {
                this._CATEGORY = value;
                this.OnPropertyChanged("CATEGORY");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CATEGORY _CATEGORY;
        /// <summary>
        /// There are no comments for ITEM in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ITEM> ITEM
        {
            get
            {
                return this._ITEM;
            }
            set
            {
                this._ITEM = value;
                this.OnPropertyChanged("ITEM");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ITEM> _ITEM = new global::System.Data.Services.Client.DataServiceCollection<ITEM>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for USER in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<USER> USER
        {
            get
            {
                return this._USER;
            }
            set
            {
                this._USER = value;
                this.OnPropertyChanged("USER");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<USER> _USER = new global::System.Data.Services.Client.DataServiceCollection<USER>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RSSFeedDatabaseModel.ITEM in the schema.
    /// </summary>
    /// <KeyProperties>
    /// item_id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ITEM")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("item_id")]
    public partial class ITEM : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ITEM object.
        /// </summary>
        /// <param name="item_id">Initial value of item_id.</param>
        /// <param name="item_title">Initial value of item_title.</param>
        /// <param name="item_link">Initial value of item_link.</param>
        /// <param name="item_description">Initial value of item_description.</param>
        /// <param name="feed_id">Initial value of feed_id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ITEM CreateITEM(long item_id, string item_title, string item_link, string item_description, long feed_id)
        {
            ITEM iTEM = new ITEM();
            iTEM.item_id = item_id;
            iTEM.item_title = item_title;
            iTEM.item_link = item_link;
            iTEM.item_description = item_description;
            iTEM.feed_id = feed_id;
            return iTEM;
        }
        /// <summary>
        /// There are no comments for Property item_id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long item_id
        {
            get
            {
                return this._item_id;
            }
            set
            {
                this.Onitem_idChanging(value);
                this._item_id = value;
                this.Onitem_idChanged();
                this.OnPropertyChanged("item_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _item_id;
        partial void Onitem_idChanging(long value);
        partial void Onitem_idChanged();
        /// <summary>
        /// There are no comments for Property item_title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string item_title
        {
            get
            {
                return this._item_title;
            }
            set
            {
                this.Onitem_titleChanging(value);
                this._item_title = value;
                this.Onitem_titleChanged();
                this.OnPropertyChanged("item_title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _item_title;
        partial void Onitem_titleChanging(string value);
        partial void Onitem_titleChanged();
        /// <summary>
        /// There are no comments for Property item_link in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string item_link
        {
            get
            {
                return this._item_link;
            }
            set
            {
                this.Onitem_linkChanging(value);
                this._item_link = value;
                this.Onitem_linkChanged();
                this.OnPropertyChanged("item_link");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _item_link;
        partial void Onitem_linkChanging(string value);
        partial void Onitem_linkChanged();
        /// <summary>
        /// There are no comments for Property item_description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string item_description
        {
            get
            {
                return this._item_description;
            }
            set
            {
                this.Onitem_descriptionChanging(value);
                this._item_description = value;
                this.Onitem_descriptionChanged();
                this.OnPropertyChanged("item_description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _item_description;
        partial void Onitem_descriptionChanging(string value);
        partial void Onitem_descriptionChanged();
        /// <summary>
        /// There are no comments for Property feed_id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long feed_id
        {
            get
            {
                return this._feed_id;
            }
            set
            {
                this.Onfeed_idChanging(value);
                this._feed_id = value;
                this.Onfeed_idChanged();
                this.OnPropertyChanged("feed_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _feed_id;
        partial void Onfeed_idChanging(long value);
        partial void Onfeed_idChanged();
        /// <summary>
        /// There are no comments for FEED in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public FEED FEED
        {
            get
            {
                return this._FEED;
            }
            set
            {
                this._FEED = value;
                this.OnPropertyChanged("FEED");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private FEED _FEED;
        /// <summary>
        /// There are no comments for USER in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<USER> USER
        {
            get
            {
                return this._USER;
            }
            set
            {
                this._USER = value;
                this.OnPropertyChanged("USER");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<USER> _USER = new global::System.Data.Services.Client.DataServiceCollection<USER>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RSSFeedDatabaseModel.ROLE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// role_id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ROLE")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("role_id")]
    public partial class ROLE : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ROLE object.
        /// </summary>
        /// <param name="role_id">Initial value of role_id.</param>
        /// <param name="role_name">Initial value of role_name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ROLE CreateROLE(long role_id, string role_name)
        {
            ROLE rOLE = new ROLE();
            rOLE.role_id = role_id;
            rOLE.role_name = role_name;
            return rOLE;
        }
        /// <summary>
        /// There are no comments for Property role_id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long role_id
        {
            get
            {
                return this._role_id;
            }
            set
            {
                this.Onrole_idChanging(value);
                this._role_id = value;
                this.Onrole_idChanged();
                this.OnPropertyChanged("role_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _role_id;
        partial void Onrole_idChanging(long value);
        partial void Onrole_idChanged();
        /// <summary>
        /// There are no comments for Property role_name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string role_name
        {
            get
            {
                return this._role_name;
            }
            set
            {
                this.Onrole_nameChanging(value);
                this._role_name = value;
                this.Onrole_nameChanged();
                this.OnPropertyChanged("role_name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _role_name;
        partial void Onrole_nameChanging(string value);
        partial void Onrole_nameChanged();
        /// <summary>
        /// There are no comments for USER in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<USER> USER
        {
            get
            {
                return this._USER;
            }
            set
            {
                this._USER = value;
                this.OnPropertyChanged("USER");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<USER> _USER = new global::System.Data.Services.Client.DataServiceCollection<USER>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RSSFeedDatabaseModel.STATUS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// status_id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("STATUS")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("status_id")]
    public partial class STATUS : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new STATUS object.
        /// </summary>
        /// <param name="status_id">Initial value of status_id.</param>
        /// <param name="status_name">Initial value of status_name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static STATUS CreateSTATUS(long status_id, string status_name)
        {
            STATUS sTATUS = new STATUS();
            sTATUS.status_id = status_id;
            sTATUS.status_name = status_name;
            return sTATUS;
        }
        /// <summary>
        /// There are no comments for Property status_id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long status_id
        {
            get
            {
                return this._status_id;
            }
            set
            {
                this.Onstatus_idChanging(value);
                this._status_id = value;
                this.Onstatus_idChanged();
                this.OnPropertyChanged("status_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _status_id;
        partial void Onstatus_idChanging(long value);
        partial void Onstatus_idChanged();
        /// <summary>
        /// There are no comments for Property status_name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string status_name
        {
            get
            {
                return this._status_name;
            }
            set
            {
                this.Onstatus_nameChanging(value);
                this._status_name = value;
                this.Onstatus_nameChanged();
                this.OnPropertyChanged("status_name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _status_name;
        partial void Onstatus_nameChanging(string value);
        partial void Onstatus_nameChanged();
        /// <summary>
        /// There are no comments for USER in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<USER> USER
        {
            get
            {
                return this._USER;
            }
            set
            {
                this._USER = value;
                this.OnPropertyChanged("USER");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<USER> _USER = new global::System.Data.Services.Client.DataServiceCollection<USER>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RSSFeedDatabaseModel.USER in the schema.
    /// </summary>
    /// <KeyProperties>
    /// user_id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("USER")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("user_id")]
    public partial class USER : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new USER object.
        /// </summary>
        /// <param name="user_id">Initial value of user_id.</param>
        /// <param name="user_email">Initial value of user_email.</param>
        /// <param name="user_password">Initial value of user_password.</param>
        /// <param name="status_id">Initial value of status_id.</param>
        /// <param name="role_id">Initial value of role_id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static USER CreateUSER(long user_id, string user_email, string user_password, long status_id, long role_id)
        {
            USER uSER = new USER();
            uSER.user_id = user_id;
            uSER.user_email = user_email;
            uSER.user_password = user_password;
            uSER.status_id = status_id;
            uSER.role_id = role_id;
            return uSER;
        }
        /// <summary>
        /// There are no comments for Property user_id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this.Onuser_idChanging(value);
                this._user_id = value;
                this.Onuser_idChanged();
                this.OnPropertyChanged("user_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _user_id;
        partial void Onuser_idChanging(long value);
        partial void Onuser_idChanged();
        /// <summary>
        /// There are no comments for Property user_email in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string user_email
        {
            get
            {
                return this._user_email;
            }
            set
            {
                this.Onuser_emailChanging(value);
                this._user_email = value;
                this.Onuser_emailChanged();
                this.OnPropertyChanged("user_email");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _user_email;
        partial void Onuser_emailChanging(string value);
        partial void Onuser_emailChanged();
        /// <summary>
        /// There are no comments for Property user_password in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string user_password
        {
            get
            {
                return this._user_password;
            }
            set
            {
                this.Onuser_passwordChanging(value);
                this._user_password = value;
                this.Onuser_passwordChanged();
                this.OnPropertyChanged("user_password");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _user_password;
        partial void Onuser_passwordChanging(string value);
        partial void Onuser_passwordChanged();
        /// <summary>
        /// There are no comments for Property status_id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long status_id
        {
            get
            {
                return this._status_id;
            }
            set
            {
                this.Onstatus_idChanging(value);
                this._status_id = value;
                this.Onstatus_idChanged();
                this.OnPropertyChanged("status_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _status_id;
        partial void Onstatus_idChanging(long value);
        partial void Onstatus_idChanged();
        /// <summary>
        /// There are no comments for Property role_id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long role_id
        {
            get
            {
                return this._role_id;
            }
            set
            {
                this.Onrole_idChanging(value);
                this._role_id = value;
                this.Onrole_idChanged();
                this.OnPropertyChanged("role_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _role_id;
        partial void Onrole_idChanging(long value);
        partial void Onrole_idChanged();
        /// <summary>
        /// There are no comments for ROLE in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ROLE ROLE
        {
            get
            {
                return this._ROLE;
            }
            set
            {
                this._ROLE = value;
                this.OnPropertyChanged("ROLE");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ROLE _ROLE;
        /// <summary>
        /// There are no comments for STATUS in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public STATUS STATUS
        {
            get
            {
                return this._STATUS;
            }
            set
            {
                this._STATUS = value;
                this.OnPropertyChanged("STATUS");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private STATUS _STATUS;
        /// <summary>
        /// There are no comments for ITEM in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ITEM> ITEM
        {
            get
            {
                return this._ITEM;
            }
            set
            {
                this._ITEM = value;
                this.OnPropertyChanged("ITEM");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ITEM> _ITEM = new global::System.Data.Services.Client.DataServiceCollection<ITEM>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for FEED in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<FEED> FEED
        {
            get
            {
                return this._FEED;
            }
            set
            {
                this._FEED = value;
                this.OnPropertyChanged("FEED");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<FEED> _FEED = new global::System.Data.Services.Client.DataServiceCollection<FEED>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
