USE [master]
GO

/****** Object:  Database [RSSFeedDatabase]    Script Date: 10/29/2011 14:08:11 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'RSSFeedDatabase')
DROP DATABASE [RSSFeedDatabase]
GO

USE [master]
GO

/****** Object:  Database [RSSFeedDatabase]    Script Date: 10/29/2011 14:08:11 ******/
CREATE DATABASE [RSSFeedDatabase] ON  PRIMARY 
( NAME = N'RSSFeedDatabase', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\RSSFeedDatabase.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RSSFeedDatabase_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\RSSFeedDatabase_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RSSFeedDatabase] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RSSFeedDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RSSFeedDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RSSFeedDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RSSFeedDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RSSFeedDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RSSFeedDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RSSFeedDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RSSFeedDatabase] SET  READ_WRITE 
GO

ALTER DATABASE [RSSFeedDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RSSFeedDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [RSSFeedDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RSSFeedDatabase] SET DB_CHAINING OFF 
GO

