//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace RSSFeedService
{
    public partial class RSSFeedDatabaseEntities : ObjectContext
    {
        public const string ConnectionString = "name=RSSFeedDatabaseEntities";
        public const string ContainerName = "RSSFeedDatabaseEntities";
    
        #region Constructors
    
        public RSSFeedDatabaseEntities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public RSSFeedDatabaseEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public RSSFeedDatabaseEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<CATEGORY> CATEGORY
        {
            get { return _cATEGORY  ?? (_cATEGORY = CreateObjectSet<CATEGORY>("CATEGORY")); }
        }
        private ObjectSet<CATEGORY> _cATEGORY;
    
        public ObjectSet<FEED> FEED
        {
            get { return _fEED  ?? (_fEED = CreateObjectSet<FEED>("FEED")); }
        }
        private ObjectSet<FEED> _fEED;
    
        public ObjectSet<ITEM> ITEM
        {
            get { return _iTEM  ?? (_iTEM = CreateObjectSet<ITEM>("ITEM")); }
        }
        private ObjectSet<ITEM> _iTEM;
    
        public ObjectSet<ROLE> ROLE
        {
            get { return _rOLE  ?? (_rOLE = CreateObjectSet<ROLE>("ROLE")); }
        }
        private ObjectSet<ROLE> _rOLE;
    
        public ObjectSet<STATUS> STATUS
        {
            get { return _sTATUS  ?? (_sTATUS = CreateObjectSet<STATUS>("STATUS")); }
        }
        private ObjectSet<STATUS> _sTATUS;
    
        public ObjectSet<USER> USER
        {
            get { return _uSER  ?? (_uSER = CreateObjectSet<USER>("USER")); }
        }
        private ObjectSet<USER> _uSER;

        #endregion
    }
}
